# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{crowd_rails}
  s.version = "0.5.11"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Stefan Wille", "Stephen Kenworthy"]
  s.date = %q{2010-11-18}
  s.description = %q{Single Sign On for Atlassian Crowd 2.0 with Ruby on Rails}
  s.email = %q{enquiries @nospam@ globalhand.org}
  s.extra_rdoc_files = [
    "LICENSE",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "LICENSE",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "crowd_rails.gemspec",
    "lib/crowd_rails.rb",
    "lib/single_sign_on.rb",
    "test/helper.rb"
  ]
  s.homepage = %q{http://github.com/crossroads/crowd_rails}
  s.require_paths = ["lib"]
  s.rubyforge_project = %q{nowarning}
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Single Sign On for Atlassian Crowd 2.0 with Ruby on Rails}
  s.test_files = [
    "test/helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

